### ISSUE TITLE
has_negate behaviour changed in gcc 8.1.0

### ISSUE THREAD

**Issue by darioizzo** [bluescarni/piranha#139] opened 2018-05-14 13:38 UTC
The piranha::has_negate type trait (v0.10) has a different behaviour in gcc 8.1.0 and clang:

```
#include <piranha/piranha.hpp>
#include <iostream>
        int main(void){
            std::cout << piranha::has_negate<unsigned short>::value << std::endl;
}
```

Output is:
g++ (v.8.1.0): 0 (which makes all piranha polynomial assert statically during compilation)
clang++: 1 (which is the desired behaviour)

Something may have changed in gcc 8.1.0 as I did not have this issue before.

**Comment by bluescarni** [comment] 2018-05-15 09:12
Thanks for the report!

I was able to reproduce the issue on my installation. This looks like a GCC 8.1 bug. I have implemented a workaround in a separate branch:

https://github.com/bluescarni/piranha/tree/gcc_8_fix

All tests compile & run cleanly now on my installation. If that works for you, I'll do a 0.11 release with the fix.

**Comment by bluescarni** [comment] 2018-05-15 09:35
Alright, I have done the 0.11 emergency release. I am closing the report.

**Closed by bluescarni** 2018-05-15 09:35 UTC
